create table public.items (
  author jsonb not null,
  created_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone null,
  id bigint generated by default as identity not null,
  meta jsonb not null,
  service_id text not null,
  updated_at timestamp with time zone not null default now(),
  url text not null,
  constraint items_pkey primary key (id),
  unique (service_id, url)
) tablespace pg_default;