create table public.items (
  id bigint generated by default as identity not null,
  channel_id text not null,
  channel_name text not null default ''::text,
  created_at timestamp with time zone not null default now(),
  deleted_at timestamp without time zone null,
  link text not null,
  meta jsonb not null,
  service_id text not null,
  service_name text not null,
  user_id text not null,
  user_name text not null,
  constraint items_pkey primary key (id)
) tablespace pg_default;